# Generated by Django 5.2.8 on 2026-06-02 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0003_alter_products_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Nombre")),
                (
                    "number_phone",
                    models.CharField(max_length=20, verbose_name="Teléfono"),
                ),
                (
                    "mail",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                ("date_register", models.DateTimeField(auto_now_add=True)),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el cliente puede seguir pidiendo fiado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ProductSold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_products",
                    models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
                ),
                (
                    "price_by",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio Unitario",
                    ),
                ),
                (
                    "price_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio Total",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.products",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.sale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto Vendido",
                "verbose_name_plural": "Productos Vendidos",
            },
        ),
    ]
