# Generated by Django 5.2.8 on 2026-05-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "name",
                    models.TextField(primary_key=True, serialize=False, unique=True),
                ),
                ("stock", models.IntegerField(default=1)),
                (
                    "unit_measurement",
                    models.TextField(
                        choices=[
                            ("unidad", "Unidad"),
                            ("libra", "Libra"),
                            ("kilo", "Kilo"),
                            ("gramo", "Gramo"),
                        ],
                        default=0,
                    ),
                ),
                ("price_by", models.IntegerField()),
            ],
            options={
                "verbose_name": "Productos",
                "verbose_name_plural": "Productos",
                "db_table": "productos",
            },
        ),
    ]
