# Generated by Django 5.2.8 on 2026-05-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="id",
            field=models.IntegerField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.TextField(unique=True),
        ),
    ]
