# Generated by Django 5.2.8 on 2026-06-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_products_id_alter_products_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
